spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/happynewyear?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    password: '0523'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: fbc763fcb9b569e877678521c3c917dcfe6664060a30250d7db58371e273b318
  access-token-expiration-millis: 86400000
  refresh-token-expiration-millis: 604800000
